# Generated by Django 6.1 on 2026-09-14 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('released_at', models.DateField()),
                ('audio_path', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
