# Generated by Django 6.1 on 2026-09-21 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('released_at', models.DateField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
